### PR TITLE
require six>=1.4 (python_consul won't work with earlier versions)

### PR DESCRIPTION
**Pull request by pawlowskimichal**
```
$ pip install 'six==1.3'

.. cut ...

$ python -c 'import consul'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "consul/__init__.py", line 3, in <module>
    from consul.std import Consul
  File "consul/std.py", line 1, in <module>
    from six.moves import urllib
ImportError: cannot import name urllib
```

Works with 1.4 up.

### CODE REVIEW

**Comment by trojkat** [comment]
:+1:

**Comment by cablehead** [comment]
Thanks for catching this

**Comment by cablehead** [comment]
Pushed to Pypi as v0.3.19

**Comment by pawlowskimichal** [comment]
@cablehead Thanks for fast merge. It's great I can undo a Thursday hack on Monday in our codebase rather than wait a month as it sometimes happens :)
